# Generated by Django 3.0.2 on 2020-08-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_owner', models.CharField(max_length=100, verbose_name='Company Owner')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('capital', models.IntegerField(default=0, verbose_name='In Millions')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
